import os
os.system('pip install requests')
os.system('pip install random')
os.system('pip install colorama')
os.system('pip install time')
os.system('pip install dhooks')
os.system('pip install requests')
os.system('pip install user_agent')
os.system('pip install colorama')
os.system('pip install pyfiglet')